In [2]:
import tensorflow as tf

from plotgraph import show_graph

In [3]:
graph = tf.Graph()
with graph.as_default():
    a  =  tf.constant(2,name="a")
    b  =  tf.constant(3,name="b")
    c  =  tf.constant(4,name="c")
    d  =  tf.constant(10,name="d")
    
    x  =  tf.add(a, b,name="x")
    y=tf.multiply(x,c)
    z=tf.div(y,d)
    print(y)
    
    g=  tf.add(x, b,name="g")
    h=  tf.multiply(g,c,name="h")
    
    with tf.Session() as sess:
        e=sess.run(z)
        print(e)
        t=sess.run(y)
        print('y=',t)

Tensor("Mul:0", shape=(), dtype=int32)
2
('y=', 20)


In [4]:
show_graph(graph)

In [5]:
a = tf.constant(5)
b = tf.constant([5])

# constant of 1d tensor (vector)
c=tf.constant([2,2],name="vector")
# constant of 2x2 tensor (matrix)
d=tf.constant([[0,1],[2,3]],name="b")


print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
#b = tf.ones((2,2))
#c = 5*tf.zeros((2,2))
#print(c)


()
(1,)
(2,)
(2, 2)


In [6]:
tf.zeros([2,3],tf.int32)
tf.ones([2,3],tf.int32)
tf.ones([2,3],8)

<tf.Tensor 'ones_1:0' shape=(2, 3) dtype=complex64>

In [7]:
#You can create constants that are sequences

In [8]:
tf.linspace(10.0,13.0,4,name="linspace")
# 'start' is 3, 'limit' is 18, 'delta' is 3


<tf.Tensor 'linspace:0' shape=(4,) dtype=float32>

In [9]:
# variable

In [10]:
W = tf.Variable(tf.zeros((2,2)), name="weights")
R = tf.Variable(tf.random_normal((2,2)), name="random_weights")


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(W))
    print(sess.run(R))

[[0. 0.]
 [0. 0.]]
[[ 0.68106866  0.6508972 ]
 [ 0.33443576 -0.86536276]]


In [11]:
# variable scope

In [12]:
with tf.variable_scope("foo"):
    with tf.variable_scope("bar"):
        v = tf.get_variable("v", [1])
assert v.name == "foo/bar/v:0"

In [13]:

with tf.variable_scope("foo"):
    v = tf.get_variable("v", [1])
assert v.name == "foo/v:0"

In [14]:

with tf.variable_scope("foo",reuse=True):
    v = tf.get_variable("v", [1])
with tf.variable_scope("foo", reuse=True):
    v1 = tf.get_variable("v", [1])
assert v1 == v

In [15]:
# Placeholders and feed_dict

In [16]:
# create a placeholder of type float 32-bit, shape is a vector of 3 elements
a=tf.placeholder(tf.float32,shape=[3])

#a = tf.Variable(tf.ones((3)), name="a")
# create a constant of type float 32-bit, shape is a vector of 3 elements
b=tf.constant([5,5,5],tf.float32)
# use the placeholder as you would a constant or a variable
c=a+b # Short for tf.add(a, b)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    #print(sess.run(a))
    print(sess.run(c,{a:[1,2,3]}))
    print(sess.run(c,{a:[10,11,12]}))
    #print(sess.run(c))

[6. 7. 8.]
[15. 16. 17.]


In [17]:
#feed multiple data points to placeholder?

In [18]:
list_of_a_values=([1,2,3],[4,5,6])
with tf.Session() as sess:
    for a_value in list_of_a_values:
        print(sess.run(c,{a:a_value}))

[6. 7. 8.]
[ 9. 10. 11.]


In [19]:
# use feed_dict

In [20]:
list_of_a_values=([1,2,3],[4,5,6])
with tf.Session() as sess:
    for a_value in list_of_a_values:
        print(sess.run(c,feed_dict={a:a_value}))

[6. 7. 8.]
[ 9. 10. 11.]


In [21]:
#Variable are also feedable

In [22]:
a=tf.add(2,3)
b=tf.multiply(a,5)
with tf.Session() as sess:
    print(sess.run(b,{a:2}))

10


In [23]:
#Compute gradients:

In [24]:
# define symbolic variables
x = tf.placeholder("float") 
y = tf.placeholder("float")

# define a function R=R(x,y)
#R = 0.127-(x*0.194/(y+0.194))
R=x*x+2*y*y

# The derivative of R with respect to y
Rdx,Rdy = tf.gradients(R, [x,y]); 

# Launch a session for the default graph to comput dR/dy at (x,y)=(0.362, 0.556)
sess = tf.Session()
dx = sess.run(Rdx, {x:2,y:1})
dy = sess.run(Rdy, {x:2,y:3})
print(dx)
print(dy)

4.0
12.0


('A=', array([[-1.6706126 ,  0.01952025],
       [-0.1694668 ,  1.5714623 ],
       [ 1.315937  , -0.81158847]], dtype=float32))
('B=', array([[ 2.6373768 ,  0.0698636 ,  0.06585131],
       [-0.24940877,  0.9251737 , -0.16281162]], dtype=float32))
('C=', array([[3.24796  , 2.3473954, 2.5231273],
       [2.3638191, 1.6681817, 1.8870158],
       [1.2953143, 1.2943413, 0.5545496]], dtype=float32))
('D=', array([[ -4071835.2,  10732677. ,  25844544. ],
       [ -7734767.5,  20387552. ,  49093720. ],
       [  2349573.5,  -6193076.5, -14913081. ]], dtype=float32))


('y=', array([[0.9241418]], dtype=float32))
('y=', array([[0.98201376]], dtype=float32))
('y=', array([[0.9241418]], dtype=float32))
